name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Getting the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: BUILD
        run: npm run build
      - name: TESTS
        run: npm test
      - name: E2E TESTS
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000
      - name: Deploy web services
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pokedex-l'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D0B669B2E160495D92865A4B35EF41DE }}
          package: .
